jobs:
- name: get
  plan:
  - get: git
    trigger: true
resources:
- name: git
  type: dynamic-metalink
  source:
    version_check: |
      git ls-remote --tags https://github.com/git/git.git \
        | cut -f2 \
        | grep -v '\^{}' \
        | grep -E '^refs/tags/v.+$' \
        | sed -E 's/^refs\/tags\/v(.+)$/\1/' \
        | grep -E '^\d+\.\d+\.\d+\w*$' \
        | grep -v -- -
    metalink_get: |
      export name="git-${version}.tar.gz"
      export hash=$( curl -s "https://mirrors.edge.kernel.org/pub/software/scm/git/sha256sums.asc" | grep "$name" | awk '{ print $1 }' )
      jq -n '
        env.name | {
          "files": [
            { "name": .,
              "urls": [ { "url": "https://www.kernel.org/pub/software/scm/git/\(.)" } ],
              "hashes": [ { "type": "sha-256", "hash": env.hash } ] } ] }'
resource_types:
- name: dynamic-metalink
  type: docker-image
  source:
    repository: dpb587/dynamic-metalink-resource
