jobs:
- name: get
  plan:
  - get: golang
    trigger: true
resources:
- name: golang
  type: dynamic-metalink
  source:
    version_check: |
      curl -s https://golang.org/dl/?mode=json | jq -r '.[].version[2:]'
    metalink_get: |
      curl -s https://golang.org/dl/?mode=json | jq '
        map(select(.version[2:] == env.version)) | map({
          "files": (.files | map({
            "name": .filename,
            "size": .size,
            "urls": [ { "url": "https://dl.google.com/go/\(.filename)" } ],
            "hashes": [ { "type": "sha-256", "hash": .sha256 } ] } ) ) } )[]'
    version: 1.9.x
    include_files:
    - go*.linux-amd64.tar.gz
resource_types:
- name: dynamic-metalink
  type: docker-image
  source:
    repository: dpb587/dynamic-metalink-resource
