jobs:
- name: get
  plan:
  - get: libxml2
    trigger: true
resources:
- name: libxml2
  type: dynamic-metalink
  source:
    version_check: |
      curl -s -l ftp://xmlsoft.org/libxml2/ \
        | grep -E '^libxml2-.+.tar.gz$' \
        | sed -E 's/^libxml2-(.+)\.tar.gz$/\1/' \
        | grep -E '^\d+\.\d+\.\d+\w*$' \
    metalink_get: |
      jq -n '
        "libxml2-\(env.version).tar.gz" | {
          "files": [
            { "name": .,
              "urls": [ { "url": "ftp://xmlsoft.org/libxml2/\(.)" } ] } ] }'
resource_types:
- name: dynamic-metalink
  type: docker-image
  source:
    repository: dpb587/dynamic-metalink-resource
