jobs:
- name: get
  plan:
  - get: pcre
    trigger: true
resources:
- name: pcre
  type: dynamic-metalink
  source:
    version_check: |
      curl -s -l ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/ \
        | grep -E '^pcre-.+.tar.gz$' \
        | sed -E 's/^pcre-(.+)\.tar.gz$/\1/'
    metalink_get: |
      jq -n '
        "pcre-\(env.version).tar.gz" | {
          "files": [
            { "name": .,
              "urls": [ { "url": "ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/\(.)" } ] } ] }'
resource_types:
- name: dynamic-metalink
  type: docker-image
  source:
    repository: dpb587/dynamic-metalink-resource
