jobs:
- name: get
  plan:
  - get: php7
    trigger: true
resources:
- name: php7
  type: dynamic-metalink
  source:
    version_check: |
      curl -s 'https://secure.php.net/releases/index.php?json&max=128&version=7' \
        | jq -r 'keys[]'
    metalink_get: |
      curl -s 'https://secure.php.net/releases/index.php?json&max=128&version=7' | jq '
        to_entries | map(select(.key == env.version)) | map(.value | {
          "files": (.source | map({
            "name": .filename,
            "urls": [ { "url": "http://us1.php.net/distributions/\(.filename)" } ],
            "hashes": [ { "type": "sha-256", "hash": .sha256 } ] } ) ) } )[]'
resource_types:
- name: dynamic-metalink
  type: docker-image
  source:
    repository: dpb587/dynamic-metalink-resource
